name: Kotlin CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Firebase config
        run: echo "${{ secrets.FIREBASE_CONFIG }}" > app/src/google-services.json

      - name: Set up VK config
        run: echo "${{ secrets.VKID_SECRETS }}" > app/secrets.properties

      - name: Build debug
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: memify-debug-${{ github.sha }}
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          retention-days: 14

  static_analysis:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout static code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
            java-version: "17"
            distribution: "temurin"

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
            reviewdog_version: latest

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
            path: ~/.gradle/caches
            key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle') }}
            restore-keys: |
                gradle-caches-${{ runner.os }}-

      - name: Grant execute permissions for Ktlint and Detekt
        run: chmod +x ./ktlint.sh ./detekt.sh

      - name: Ktlint Check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./ktlint.sh

      - name: Detekt Check
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./detekt.sh
